src/objects/Subscription_Form__c.object
<CustomObject>
    <fields>
        <fullName>Channels_Selected__c</fullName>
        <label>Channels Selected</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscription Forms</relationshipLabel>
        <relationshipName>Subscription_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription Form</label>
    <nameField>
        <displayFormat>SF - {0000}</displayFormat>
        <label>Subscription Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/forceVFTestController.cls
public class forceVFTestController {
    public String opptyName{get;set;}
    public List<Subscription_Form__c> sList{get;set;}
    public forceVFTestController(ApexPages.StandardController controller) {
    
    }
    public void getForm(){
    //opptyName='aa1';
    sList = [SELECT id,Name,Email__c, Password__c, Opportunity__r.Name, Opportunity__r.StageName,Name__c, Channels_Selected__c, Opportunity__r.LeadSource FROM Subscription_Form__c WHERE Opportunity__r.Name = :opptyName LIMIT 1];
    opptyName=sList[0].Opportunity__r.Name;
    }
    public PageReference save1(){
    System.debug('Save fn');
     if(sList != NULL){
      upsert sList;
      System.debug('upserted');
     }
     Blob fileBody=Blob.valueOf('test');
     Attachment attachment= new Attachment();
     attachment.ParentId = sList[0].Id;
attachment.IsPrivate = false;
attachment.body = fileBody;
attachment.Name='Test File.pdf';


    insert attachment;
     
      return Page.forceVFTest;
    }
}